---
- name: configuration kubernetes
  debug:
     msg: "configuration kubernetes"
- name: "Test master connection"
  ping:

- name: Change IP address
  replace:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '{{ template_server["ip_address"] }}'
    replace: '{{ kubernetes_master["ip_address"] }}'
  tags:
    - master 

- name: reboot the master
  reboot:
    reboot_timeout: 10
  tags:
    - master 