---
- name: configuration swarm
  debug:
     msg: "configuration swarm"
- name: "Test master connection"
  ping:

- name: Change IP address
  replace:
    path: /etc/network/interfaces
    regexp: '{{ template_server["ip_address"] }}'
    replace: '{{ swarm_master["ip_address"] }}'
  tags:
    - master 

- name: Change IP address
  replace:
    path: /etc/network/interfaces
    regexp: '{{ template_server["ip_address"] }}'
    replace: '{{ swarm_workers["worker1"]["ip_address"] }}'
  tags:
    - worker1 

- name: Change IP address
  replace:
    path: /etc/network/interfaces
    regexp: '{{ template_server["ip_address"] }}'
    replace: '{{ swarm_workers["worker2"]["ip_address"] }}'
  tags:
    - worker2  

- name: reboot the server
  reboot:
    reboot_timeout: 10  
  tags:
    - reboot


- name: john to master
