vsphere_user = "administrator@stqiu.local"
vsphere_password = "Polycom!12"
vsphere_server = "rprm121.pctc-rprmqa.com"
vcenter_datacenter = "jeck"
vsphere_datastore = "datastore/ExtHDD2"
vcenter_cluster = "/jeck/host/172.21.120.10"
